version: '3.8'

services:
    devcolumn:
        container_name: devcolumn
        build:
            context: .
            dockerfile: ./Dockerfile
        command: run_devcolumn
        volumes:
            - devcolumn-logs:/app/devcolumn/logs
        ports:
            - 8000:8000
        env_file:
            - ./docker/dev.env
        depends_on:
            db:
                condition: service_healthy
        networks:
            - a-net
        

    db:
        container_name: db_devcolumn
        image: postgres:15
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - postgres-log:/var/log/postgresql
        ports:
            - "5432:5432"
        env_file:
            - ./docker/dev.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - a-net

networks:
    a-net:
        driver: bridge

volumes:
    devcolumn-logs:
    postgres-data: 
    postgres-log: 